name: PR Tests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Lint code
      run: |
        ruff check synthetic_data_kit tests
        ruff format --check synthetic_data_kit tests

    - name: Run tests
      env:
        PROJECT_TEST_ENV: "1"
        API_ENDPOINT_KEY: "mock-api-key-for-testing"
      run: |
        pytest tests/

    - name: Run coverage check
      env:
        PROJECT_TEST_ENV: "1"
        API_ENDPOINT_KEY: "mock-api-key-for-testing"
      run: |
        pytest --cov=synthetic_data_kit --cov-report=term-missing tests/

    - name: Comment PR with Results
      uses: actions/github-script@v7
      if: always()
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const testResults = process.env.TEST_RESULTS || 'Test results not available';

          let comment = `## PR Test Results

          ### Lint Status: ${{ job.status == 'success' ? '✅ Passed' : '❌ Failed' }}

          ### Test Status: ${{ job.status == 'success' ? '✅ Passed' : '❌ Failed' }}

          Please make sure all tests pass before merging this PR.
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
