name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      confirm_publish:
        description: 'Confirm publishing to PyPI'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

permissions:
  contents: read
  id-token: write  # For trusted publishing to PyPI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Verify version
      run: |
        # Extract version from pyproject.toml
        VERSION=$(grep -m 1 'version' pyproject.toml | cut -d '"' -f 2)
        echo "Package version: $VERSION"

        # Check if this version already exists on PyPI
        if pip index versions synthetic-data-kit 2>/dev/null | grep -q "$VERSION"; then
          echo "Error: Version $VERSION already exists on PyPI"
          exit 1
        fi
        echo "Version check passed: $VERSION is not on PyPI yet"

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Publish to PyPI
      if: github.event_name == 'release' || github.event.inputs.confirm_publish == 'yes'
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
